if not SharedMedia then return end

--background:
    SharedMedia:Register("background", "Hal BG", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\HalBackground")
    --SharedMedia:Register("background", "Moo", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\moo")
    --SharedMedia:Register("background", "Moo2", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\moo2")
    SharedMedia:Register("background", "Glass", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\Wglass")
    SharedMedia:Register("background", "Melli", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\Melli")
    SharedMedia:Register("background", "Ruben", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\Ruben")
    --SharedMedia:Register("background", "Outline", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\Outline")
    --SharedMedia:Register("background", "Litestep", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\LiteStep")
    SharedMedia:Register("background", "Glamour4", "Interface\\Addons\\CustomMedia\\Media\\Backgrounds\\Glamour4")
    --SharedMedia:Register("background", "Star4", "Interface\\Cooldown\\star4")
    --SharedMedia:Register("background", "Starburst", "Interface\\Cooldown\\starburst")
    --SharedMedia:Register("background", "Ping4", "Interface\\Cooldown\\ping4")
    --SharedMedia:Register("background", "Glowstar", "Interface\\BUTTONS\\GLOWSTAR")

--border:
    SharedMedia:Register("border", "Hal Border", "Interface\\Addons\\CustomMedia\\Media\\Borders\\HalBorder")
    SharedMedia:Register("border", "SimpleSquare2", "Interface\\Addons\\CustomMedia\\Media\\Borders\\SimpleSquare2.blp")
    SharedMedia:Register("border", "pHishBorder3", "Interface\\Addons\\CustomMedia\\Media\\Borders\\pHishBorder3.blp")
    --SharedMedia:Register("border", "SeerahScalloped", [[Interface\Addons\CustomMedia\Media\Borders\SeerahScalloped.blp]])
    --SharedMedia:Register("border", "Hal Border2", "Interface\\Addons\\CustomMedia\\Media\\Borders\\HalBorder2")
    --SharedMedia:Register("border", "RothSquare", "Interface\\Addons\\CustomMedia\\Media\\Borders\\roth")

--font:
    --SharedMedia:Register("font", "You Rook Marbelous", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\YouRookMarbelous.ttf")
    --SharedMedia:Register("font", "Avant Garde", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\AvantGarde.ttf")
    --SharedMedia:Register("font", "Expressway RG", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Expressway_Rg.ttf")
    SharedMedia:Register("font", "Expressway RG Bold", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Expressway_Rg_Bold.ttf")
    --SharedMedia:Register("font", "Sansation", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Sansation.ttf")
    --SharedMedia:Register("font", "Hooge", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Hooge.ttf")
    --SharedMedia:Register("font", "Swis721", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Swis721.ttf")
    --SharedMedia:Register("font", "PT Sans Narrow", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\PT_Sans_Narrow.ttf")
    --SharedMedia:Register("font", "Tempesta Five", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\pf_tempesta_five.ttf")
    --SharedMedia:Register("font", "Futura", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\FuturaMediumBT.ttf")
    --SharedMedia:Register("font", "Visitor2", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\visitor2.ttf")
    --SharedMedia:Register("font", "Samson", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Sam.ttf")
    --SharedMedia:Register("font", "Accident", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Accident.ttf")
    --SharedMedia:Register("font", "ABF", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\ABF.ttf")
    SharedMedia:Register("font", "BigNoodleTitling", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\BigNoodleTitling.ttf")
    --SharedMedia:Register("font", "Tangerine", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Tangerin.ttf")
    SharedMedia:Register("font", "Myriad (lowercase)", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\lowMyriad.ttf")
    SharedMedia:Register("font", "Myriad Semibold", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\myriadprosemibold.ttf")
    SharedMedia:Register("font", "Killa", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\killa.ttf")
    SharedMedia:Register("font", "VikingSquad", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\vikingsquad.ttf")
    SharedMedia:Register("font", "VikingSquad Bold", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\vikingsquadbold.ttf")
    SharedMedia:Register("font", "Skirmisher", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\skirmisher.ttf")
    SharedMedia:Register("font", "Fira Mono", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\FiraMono-Regular.ttf")
    SharedMedia:Register("font", "M+ Regular", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\mplus-1mn-regular.ttf")
    SharedMedia:Register("font", "M+ Medium", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\mplus-1mn-medium.ttf")
    --SharedMedia:Register("font", "Spy Agency", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\spyagency.ttf")
    --SharedMedia:Register("font", "TwCenMT", "Interface\\Addons\\CustomMedia\\Media\\Fonts\\Tw_Cen_MT_Bold.ttf")

--sound:
    SharedMedia:Register("sound", "Valkyr", 554029)
    SharedMedia:Register("sound", "Simon Tick", 568232)

--statusbar:
    SharedMedia:Register("statusbar", "Hal A", [[Interface\Addons\CustomMedia\Media\StatusBars\HalA]])
    SharedMedia:Register("statusbar", "Hal B", [[Interface\Addons\CustomMedia\Media\StatusBars\HalB]])
    SharedMedia:Register("statusbar", "Hal C", [[Interface\Addons\CustomMedia\Media\StatusBars\HalC]])
    SharedMedia:Register("statusbar", "Hal D", [[Interface\Addons\CustomMedia\Media\StatusBars\HalD]])
    SharedMedia:Register("statusbar", "Hal E", [[Interface\Addons\CustomMedia\Media\StatusBars\HalE]])
    SharedMedia:Register("statusbar", "Hal F", [[Interface\Addons\CustomMedia\Media\StatusBars\HalF]])
    SharedMedia:Register("statusbar", "Hal G", [[Interface\Addons\CustomMedia\Media\StatusBars\HalG]])
    SharedMedia:Register("statusbar", "Hal H", [[Interface\Addons\CustomMedia\Media\StatusBars\HalH]])
    SharedMedia:Register("statusbar", "Hal I", [[Interface\Addons\CustomMedia\Media\StatusBars\HalI]])
    SharedMedia:Register("statusbar", "Hal J", [[Interface\Addons\CustomMedia\Media\StatusBars\HalJ]])
    SharedMedia:Register("statusbar", "Hal K", [[Interface\Addons\CustomMedia\Media\StatusBars\HalK]])
    SharedMedia:Register("statusbar", "Hal L", [[Interface\Addons\CustomMedia\Media\StatusBars\HalL]])
    SharedMedia:Register("statusbar", "Hal M", [[Interface\Addons\CustomMedia\Media\StatusBars\HalM]])
    SharedMedia:Register("statusbar", "Hal N", [[Interface\Addons\CustomMedia\Media\StatusBars\HalN]])
    SharedMedia:Register("statusbar", "Hal O", [[Interface\Addons\CustomMedia\Media\StatusBars\HalO]])
    SharedMedia:Register("statusbar", "Hal P", [[Interface\Addons\CustomMedia\Media\StatusBars\HalP]])
    SharedMedia:Register("statusbar", "Hal Q", [[Interface\Addons\CustomMedia\Media\StatusBars\HalQ]])
    SharedMedia:Register("statusbar", "Hal R", [[Interface\Addons\CustomMedia\Media\StatusBars\HalR]])
    SharedMedia:Register("statusbar", "Hal S", [[Interface\Addons\CustomMedia\Media\StatusBars\HalS]])
    SharedMedia:Register("statusbar", "Hal T", [[Interface\Addons\CustomMedia\Media\StatusBars\HalT]])
    SharedMedia:Register("statusbar", "Hal U", [[Interface\Addons\CustomMedia\Media\StatusBars\HalU]])
    SharedMedia:Register("statusbar", "Hal V", [[Interface\Addons\CustomMedia\Media\StatusBars\HalV]])
    SharedMedia:Register("statusbar", "Hal W", [[Interface\Addons\CustomMedia\Media\StatusBars\HalW]])
    SharedMedia:Register("statusbar", "Neal", [[Interface\Addons\CustomMedia\Media\StatusBars\Neal]])
    SharedMedia:Register("statusbar", "nin", [[Interface\Addons\CustomMedia\Media\StatusBars\nin]])
    SharedMedia:Register("statusbar", "Kui", [[Interface\Addons\CustomMedia\Media\StatusBars\kui]])
    --SharedMedia:Register("statusbar", "Aluminium",        [[Interface\Addons\CustomMedia\Media\StatusBars\Aluminium]])
    SharedMedia:Register("statusbar", "Armory", [[Interface\Addons\CustomMedia\Media\StatusBars\Armory]])
    --SharedMedia:Register("statusbar", "BantoBar", [[Interface\Addons\CustomMedia\Media\StatusBars\BantoBar]])
    SharedMedia:Register("statusbar", "Empty", [[Interface\Addons\CustomMedia\Media\StatusBars\Empty]])
    --SharedMedia:Register("statusbar", "Flat", [[Interface\Addons\CustomMedia\Media\StatusBars\Flat]])
    --SharedMedia:Register("statusbar", "Glamour", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour]])
    --SharedMedia:Register("statusbar", "Glamour2", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour2]])
    --SharedMedia:Register("statusbar", "Glamour3", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour3]])
    SharedMedia:Register("statusbar", "Glamour4", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour4]])
    --SharedMedia:Register("statusbar", "Glamour5", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour5]])
    --SharedMedia:Register("statusbar", "Glamour6", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour6]])
    --SharedMedia:Register("statusbar", "Glamour7", [[Interface\Addons\CustomMedia\Media\StatusBars\Glamour7]])
    --SharedMedia:Register("statusbar", "Melli", [[Interface\Addons\CustomMedia\Media\StatusBars\Melli]])
    --SharedMedia:Register("statusbar", "Melli Dark", [[Interface\Addons\CustomMedia\Media\StatusBars\MelliDark]])
    --SharedMedia:Register("statusbar", "Melli Dark Rough", [[Interface\Addons\CustomMedia\Media\StatusBars\MelliDarkRough]])
    --SharedMedia:Register("statusbar", "Minimalist", [[Interface\Addons\CustomMedia\Media\StatusBars\Minimalist]])
    SharedMedia:Register("statusbar", "Ruben", [[Interface\Addons\CustomMedia\Media\StatusBars\Ruben]])
    --SharedMedia:Register("statusbar", "Smooth", [[Interface\Addons\CustomMedia\Media\StatusBars\Smooth]])
    --SharedMedia:Register("statusbar", "Smooth v2", [[Interface\Addons\CustomMedia\Media\StatusBars\Smoothv2]])
    --SharedMedia:Register("statusbar", "fer01", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer1]])
    --SharedMedia:Register("statusbar", "fer02", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer2]])
    --SharedMedia:Register("statusbar", "fer03", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer3]])
    --SharedMedia:Register("statusbar", "fer04", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer4]])
    --SharedMedia:Register("statusbar", "fer05", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer5]])
    --SharedMedia:Register("statusbar", "fer06", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer6]])
    --SharedMedia:Register("statusbar", "fer07", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer7]])
    --SharedMedia:Register("statusbar", "fer08", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer8]])
    --SharedMedia:Register("statusbar", "fer09", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer9]])
    --SharedMedia:Register("statusbar", "fer10", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer10]])
    --SharedMedia:Register("statusbar", "fer11", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer11]])
    --SharedMedia:Register("statusbar", "fer12", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer12]])
    --SharedMedia:Register("statusbar", "fer13", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer13]])
    --SharedMedia:Register("statusbar", "fer14", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer14]])
    --SharedMedia:Register("statusbar", "fer15", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer15]])
    SharedMedia:Register("statusbar", "fer16", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer16]])
    --SharedMedia:Register("statusbar", "fer17", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer17]])
    SharedMedia:Register("statusbar", "fer18", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer18]])
    --SharedMedia:Register("statusbar", "fer19", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer19]])
    --SharedMedia:Register("statusbar", "fer20", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer20]])
    --SharedMedia:Register("statusbar", "fer21", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer21]])
    --SharedMedia:Register("statusbar", "fer22", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer22]])
    --SharedMedia:Register("statusbar", "fer23", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer23]])
    --SharedMedia:Register("statusbar", "fer24", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer24]])
    --SharedMedia:Register("statusbar", "fer25", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer25]])
    --SharedMedia:Register("statusbar", "fer26", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer26]])
    --SharedMedia:Register("statusbar", "fer27", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer27]])
    --SharedMedia:Register("statusbar", "fer28", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer28]])
    --SharedMedia:Register("statusbar", "fer29", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer29]])
    --SharedMedia:Register("statusbar", "fer30", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer30]])
    --SharedMedia:Register("statusbar", "fer31", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer31]])
    --SharedMedia:Register("statusbar", "fer32", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer32]])
    --SharedMedia:Register("statusbar", "fer33", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer33]])
    --SharedMedia:Register("statusbar", "fer34", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer34]])
    --SharedMedia:Register("statusbar", "fer35", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer35]])
    --SharedMedia:Register("statusbar", "fer36", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer36]])
    --SharedMedia:Register("statusbar", "fer37", [[Interface\AddOns\CustomMedia\Media\StatusBars\fer37]])
    --SharedMedia:Register("statusbar", "Tap1", [[Interface\AddOns\CustomMedia\Media\StatusBars\tap1]])
    SharedMedia:Register("statusbar", "Tap2", [[Interface\AddOns\CustomMedia\Media\StatusBars\tap2]])
    --SharedMedia:Register("statusbar", "Tap3", [[Interface\AddOns\CustomMedia\Media\StatusBars\tap3]])
    --SharedMedia:Register("statusbar", "Tap4", [[Interface\AddOns\CustomMedia\Media\StatusBars\tap4]])